# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm_group
  joint_model_group_pose: default
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_yaw
    - shoulder_pitch
    - elbow
    - wrist
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
right_arm_position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_yaw
    - shoulder_pitch
    - elbow
    - wrist

right_arm_position_group_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - shoulder_yaw 
    - shoulder_pitch 
    - elbow
    - wrist
  gains:
    shoulder_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

right_arm_effort_controller:
  type: effort_controller/JointEffortController
  joints:
    - shoulder_pitch
    - elbow
    - wrist
    - shoulder_yaw
  
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:

  - name: right_arm_position_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pitch
      - elbow
      - wrist
      - shoulder_yaw


  # - name: right_arm_position_trajectory_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - shoulder_pitch
  #     - elbow
  #     - wrist
  #     - shoulder_yaw

/gazebo_ros_control:   
  pid_gains:
    shoulder_yaw:
      p: 100.0
      i: 0.01 
      d: 10.0
    shoulder_pitch:
      p: 100.0
      i: 0.01 
      d: 10.0
    wrist:
      p: 100.0
      i: 0.01 
      d: 10.0
    elbow:
      p: 100.0
      i: 0.01 
      d: 10.0
