controller_list:
 - name: right_arm_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - shoulder_yaw
     - shoulder_pitch
     - elbow
     - wrist